apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:           
      nodeSelector:
        kubernetes.io/hostname: k3s-server-01-225
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
        runAsGroup: 65534
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 65534:65534 /prometheus && chown -R 65534:65534 /etc/prometheus"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:v3.12.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
            - name: data
              mountPath: /prometheus
      volumes:
        - name: config
          hostPath:
            path: /opt/app-data/monitoring-stack/prometheus/config
            type: Directory
        - name: data
          hostPath:
            path: /opt/app-data/monitoring-stack/prometheus/data
            type: DirectoryOrCreate
