apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-db
  namespace: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:12.3
          args: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: "nextcloud_db"
            - name: MYSQL_USER
              value: "rolf"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          hostPath:
            path: /opt/app-data/storage-stack/nextcloud/db
            type: DirectoryOrCreate
