---
# Portainer agent telepítése
- name: Portainer Agent telepítése
  community.docker.docker_container:
    name: portainer_agent
    image: portainer/agent:2.42.0
    state: started
    restart_policy: always
    recreate: yes 
    published_ports:
      - "{{ agent_port | default('9005') }}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
