apiVersion: v1
kind: Service
metadata:
  name: gotify-service
  namespace: notification
spec:
  selector:
    app: gotify
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080 
